baseURL = "https://www.abledenthusiast.com"
languageCode = "en-us"
title = "Abledenthusiast"
theme = "ananke"
sectionPagesMenu = "main"



[params]
    favicon = "images/memoji-square.png"
    github = "https://www.github.com/abledenthusiast"
    linkedin = "https://www.linkedin.com/in/abledenthusiast"
    instagram = "https://www.instagram.com/abledenthusiast/"
    #background_color_class = "bg-gray"
    featured_image = "/images/background.jpeg"
    url = "https://www.abledenthusiast.com"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "mydeployment"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
URL = "gs://www.abledenthusiast.com"

    